config/routes.rb
Rails.application.routes.draw do
  resources :requests

  root 'requests#lookup'  
  post 'requests/lookup' => 'requests#lookup'

end

app/models/key.rb
class Key < ActiveRecord::Base
end

app/models/request.rb
require 'rubygems'
require 'whois'

class Request

	#This is a generic class for checking Key authenticity and sending requests to the engine

	attr_accessor :domain
	attr_accessor :body

    def initialize
        	@domain = nil
        	@body = nil
    end
    # sounds stupid but rails want it that way...
    def lookup(domain)
    	if domain != (nil&&true&&"")
        	c = Whois::Client.new
			@body = c.lookup(domain)
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
#  before_action :set_request, only: [:lookup]


  def lookup
    
    domain = params[:domain]
    @request = Request.new.lookup(domain)
    respond_to do |format|
      if @request != nil
        format.html {}
        format.json { render :new, status: :searched, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/requests/_form.html.erb
<%= form_tag '/requests/lookup' do %>

    <%=label_tag 'Domaine' %>
    <%=text_field_tag 'domain'%>

    <%= submit_tag 'Rechercher' %>


<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/lookup.html.erb
<%= render 'form' %> <br/>
<% if @request != nil %>
	
	Domain : <%= @request.domain %> <br/>
	Domain : <%= @request.registrar %> <br/>

<% end %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>